#!/bin/bash

echo Running test...
echo

echo Running simulation_1
python3 simulation_1.py

echo
echo Running simulation_2
python3 simulation_2.py

echo
echo Running simulation_3
python3 simulation_3.py

echo
echo Test complete.

